name: 'Get Release Info'
description: 'Get the meta data of the latest release or by id or tag, including draft releases.'
author: 'Simon Ihmig'
inputs:
  token:
    description: The Github token used for authentication.
    required: true
  owner:
    description: Name of the owner of the repo, taken from current repo by default.
    required: false
  repo:
    description: Name of the repository, taken from current repo by default.
    required: false
  id:
    description: The ID to identify the release.
    required: false
  tag_name:
    description: Tag name to identify the release.
    required: false
  latest:
    description: Will fetch the latest release if set to true.
    required: false
  draft:
    description: Set to true if you are looking for an unpublished draft release
    required: false
outputs:
  id:
    description: The ID of the Release
  url:
    description: The release url
  html_url:
    description: The url users can navigate to in order to view the release
  assets_url:
    description: The release assets url
  upload_url:
    description: The url for uploading assets to the release
  name:
    description: The release name
  tag_name:
    description: The git tag associated with the release
  draft:
    description: Is draft
  prerelease:
    description: Is pre-release
  target_commitish:
    description: The release was create to which target branch
  created_at:
    description: Created date
  published_at:
    description: Published date
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: tag
  color: orange